# Generated by Django 4.0 on 2022-01-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CollegeSubject',
            fields=[
                ('SubjectCode', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('SubjectName', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='StudentRecord',
            fields=[
                ('StudentId', models.AutoField(primary_key=True, serialize=False)),
                ('Firstname', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('MeanMarks', models.DecimalField(decimal_places=2, max_digits=5)),
                ('StudGrade', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='StudentSubjectRec',
            fields=[
                ('StudentSubjRecId', models.AutoField(primary_key=True, serialize=False)),
                ('SubjectCode', models.CharField(max_length=20)),
                ('SubjectScore', models.IntegerField()),
            ],
        ),
    ]
