# Generated by Django 4.0 on 2022-01-02 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_studrecman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsubjectrec',
            name='StudentId',
            field=models.IntegerField(default=1),
        ),
    ]
